### ISSUE TITLE
MVP

### ISSUE THREAD

**Issue by g4s8** [artipie/docker-adapter#1]
Working docker registry storage adapter.

 - [x] - #2
 - [ ] - #5
 - [x] - #6
 - [x] - #7
 - [ ] - #10 
 - [ ] - #11
 - [x] - #12 
 - [x] - #13
 - [x] - #17

**Comment by g4s8** [comment]
@rultor hello

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#2](https://github.com/artipie/docker-adapter/issues/2) is still not solved.

**Comment by 0pdd** [comment]
@g4s8 2 puzzles [#2](https://github.com/artipie/docker-adapter/issues/2), [#5](https://github.com/artipie/docker-adapter/issues/5) are still not solved.

**Comment by 0pdd** [comment]
@g4s8 3 puzzles [#5](https://github.com/artipie/docker-adapter/issues/5), [#6](https://github.com/artipie/docker-adapter/issues/6), [#7](https://github.com/artipie/docker-adapter/issues/7) are still not solved; solved: [#2](https://github.com/artipie/docker-adapter/issues/2).

**Comment by 0pdd** [comment]
@g4s8 4 puzzles [#10](https://github.com/artipie/docker-adapter/issues/10), [#11](https://github.com/artipie/docker-adapter/issues/11), [#5](https://github.com/artipie/docker-adapter/issues/5), [#7](https://github.com/artipie/docker-adapter/issues/7) are still not solved; solved: [#2](https://github.com/artipie/docker-adapter/issues/2), [#6](https://github.com/artipie/docker-adapter/issues/6).

**Comment by 0pdd** [comment]
@g4s8 6 puzzles [#10](https://github.com/artipie/docker-adapter/issues/10), [#11](https://github.com/artipie/docker-adapter/issues/11), [#12](https://github.com/artipie/docker-adapter/issues/12), [#13](https://github.com/artipie/docker-adapter/issues/13), [#5](https://github.com/artipie/docker-adapter/issues/5), [#7](https://github.com/artipie/docker-adapter/issues/7) are still not solved; solved: [#2](https://github.com/artipie/docker-adapter/issues/2), [#6](https://github.com/artipie/docker-adapter/issues/6).

**Comment by 0pdd** [comment]
@g4s8 5 puzzles [#10](https://github.com/artipie/docker-adapter/issues/10), [#11](https://github.com/artipie/docker-adapter/issues/11), [#12](https://github.com/artipie/docker-adapter/issues/12), [#13](https://github.com/artipie/docker-adapter/issues/13), [#5](https://github.com/artipie/docker-adapter/issues/5) are still not solved; solved: [#2](https://github.com/artipie/docker-adapter/issues/2), [#6](https://github.com/artipie/docker-adapter/issues/6), [#7](https://github.com/artipie/docker-adapter/issues/7).

**Comment by 0pdd** [comment]
@g4s8 5 puzzles [#10](https://github.com/artipie/docker-adapter/issues/10), [#11](https://github.com/artipie/docker-adapter/issues/11), [#13](https://github.com/artipie/docker-adapter/issues/13), [#17](https://github.com/artipie/docker-adapter/issues/17), [#5](https://github.com/artipie/docker-adapter/issues/5) are still not solved; solved: [#12](https://github.com/artipie/docker-adapter/issues/12), [#2](https://github.com/artipie/docker-adapter/issues/2), [#6](https://github.com/artipie/docker-adapter/issues/6), [#7](https://github.com/artipie/docker-adapter/issues/7).

**Comment by 0pdd** [comment]
@g4s8 5 puzzles [#10](https://github.com/artipie/docker-adapter/issues/10), [#11](https://github.com/artipie/docker-adapter/issues/11), [#17](https://github.com/artipie/docker-adapter/issues/17), [#19](https://github.com/artipie/docker-adapter/issues/19), [#5](https://github.com/artipie/docker-adapter/issues/5) are still not solved; solved: [#12](https://github.com/artipie/docker-adapter/issues/12), [#13](https://github.com/artipie/docker-adapter/issues/13), [#2](https://github.com/artipie/docker-adapter/issues/2), [#6](https://github.com/artipie/docker-adapter/issues/6), [#7](https://github.com/artipie/docker-adapter/issues/7).

**Comment by 0pdd** [comment]
@g4s8 5 puzzles [#10](https://github.com/artipie/docker-adapter/issues/10), [#11](https://github.com/artipie/docker-adapter/issues/11), [#19](https://github.com/artipie/docker-adapter/issues/19), [#25](https://github.com/artipie/docker-adapter/issues/25), [#5](https://github.com/artipie/docker-adapter/issues/5) are still not solved; solved: [#12](https://github.com/artipie/docker-adapter/issues/12), [#13](https://github.com/artipie/docker-adapter/issues/13), [#17](https://github.com/artipie/docker-adapter/issues/17), [#2](https://github.com/artipie/docker-adapter/issues/2), [#6](https://github.com/artipie/docker-adapter/issues/6), [#7](https://github.com/artipie/docker-adapter/issues/7).

**Comment by 0pdd** [comment]
@g4s8 4 puzzles [#10](https://github.com/artipie/docker-adapter/issues/10), [#11](https://github.com/artipie/docker-adapter/issues/11), [#19](https://github.com/artipie/docker-adapter/issues/19), [#5](https://github.com/artipie/docker-adapter/issues/5) are still not solved; solved: [#12](https://github.com/artipie/docker-adapter/issues/12), [#13](https://github.com/artipie/docker-adapter/issues/13), [#17](https://github.com/artipie/docker-adapter/issues/17), [#25](https://github.com/artipie/docker-adapter/issues/25), [#2](https://github.com/artipie/docker-adapter/issues/2), [#6](https://github.com/artipie/docker-adapter/issues/6), [#7](https://github.com/artipie/docker-adapter/issues/7).

**Comment by 0crat** [comment]
Job `gh:artipie/docker-adapter#1` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Comment by 0pdd** [comment]
@g4s8 4 puzzles [#10](https://github.com/artipie/docker-adapter/issues/10), [#19](https://github.com/artipie/docker-adapter/issues/19), [#36](https://github.com/artipie/docker-adapter/issues/36), [#5](https://github.com/artipie/docker-adapter/issues/5) are still not solved; solved: [#11](https://github.com/artipie/docker-adapter/issues/11), [#12](https://github.com/artipie/docker-adapter/issues/12), [#13](https://github.com/artipie/docker-adapter/issues/13), [#17](https://github.com/artipie/docker-adapter/issues/17), [#25](https://github.com/artipie/docker-adapter/issues/25), [#2](https://github.com/artipie/docker-adapter/issues/2), [#6](https://github.com/artipie/docker-adapter/issues/6), [#7](https://github.com/artipie/docker-adapter/issues/7).

**Comment by 0pdd** [comment]
@g4s8 3 puzzles [#10](https://github.com/artipie/docker-adapter/issues/10), [#36](https://github.com/artipie/docker-adapter/issues/36), [#5](https://github.com/artipie/docker-adapter/issues/5) are still not solved; solved: [#11](https://github.com/artipie/docker-adapter/issues/11), [#12](https://github.com/artipie/docker-adapter/issues/12), [#13](https://github.com/artipie/docker-adapter/issues/13), [#17](https://github.com/artipie/docker-adapter/issues/17), [#19](https://github.com/artipie/docker-adapter/issues/19), [#25](https://github.com/artipie/docker-adapter/issues/25), [#2](https://github.com/artipie/docker-adapter/issues/2), [#6](https://github.com/artipie/docker-adapter/issues/6), [#7](https://github.com/artipie/docker-adapter/issues/7).

**Comment by 0pdd** [comment]
@g4s8 3 puzzles [#10](https://github.com/artipie/docker-adapter/issues/10), [#41](https://github.com/artipie/docker-adapter/issues/41), [#5](https://github.com/artipie/docker-adapter/issues/5) are still not solved; solved: [#11](https://github.com/artipie/docker-adapter/issues/11), [#12](https://github.com/artipie/docker-adapter/issues/12), [#13](https://github.com/artipie/docker-adapter/issues/13), [#17](https://github.com/artipie/docker-adapter/issues/17), [#19](https://github.com/artipie/docker-adapter/issues/19), [#25](https://github.com/artipie/docker-adapter/issues/25), [#2](https://github.com/artipie/docker-adapter/issues/2), [#36](https://github.com/artipie/docker-adapter/issues/36), [#6](https://github.com/artipie/docker-adapter/issues/6), [#7](https://github.com/artipie/docker-adapter/issues/7).

**Comment by 0pdd** [comment]
@g4s8 4 puzzles [#10](https://github.com/artipie/docker-adapter/issues/10), [#43](https://github.com/artipie/docker-adapter/issues/43), [#44](https://github.com/artipie/docker-adapter/issues/44), [#5](https://github.com/artipie/docker-adapter/issues/5) are still not solved; solved: [#11](https://github.com/artipie/docker-adapter/issues/11), [#12](https://github.com/artipie/docker-adapter/issues/12), [#13](https://github.com/artipie/docker-adapter/issues/13), [#17](https://github.com/artipie/docker-adapter/issues/17), [#19](https://github.com/artipie/docker-adapter/issues/19), [#25](https://github.com/artipie/docker-adapter/issues/25), [#2](https://github.com/artipie/docker-adapter/issues/2), [#36](https://github.com/artipie/docker-adapter/issues/36), [#41](https://github.com/artipie/docker-adapter/issues/41), [#6](https://github.com/artipie/docker-adapter/issues/6), [#7](https://github.com/artipie/docker-adapter/issues/7).

**Comment by 0pdd** [comment]
@g4s8 4 puzzles [#10](https://github.com/artipie/docker-adapter/issues/10), [#44](https://github.com/artipie/docker-adapter/issues/44), [#47](https://github.com/artipie/docker-adapter/issues/47), [#5](https://github.com/artipie/docker-adapter/issues/5) are still not solved; solved: [#11](https://github.com/artipie/docker-adapter/issues/11), [#12](https://github.com/artipie/docker-adapter/issues/12), [#13](https://github.com/artipie/docker-adapter/issues/13), [#17](https://github.com/artipie/docker-adapter/issues/17), [#19](https://github.com/artipie/docker-adapter/issues/19), [#25](https://github.com/artipie/docker-adapter/issues/25), [#2](https://github.com/artipie/docker-adapter/issues/2), [#36](https://github.com/artipie/docker-adapter/issues/36), [#41](https://github.com/artipie/docker-adapter/issues/41), [#43](https://github.com/artipie/docker-adapter/issues/43), [#6](https://github.com/artipie/docker-adapter/issues/6), [#7](https://github.com/artipie/docker-adapter/issues/7).

**Comment by 0pdd** [comment]
@g4s8 3 puzzles [#44](https://github.com/artipie/docker-adapter/issues/44), [#47](https://github.com/artipie/docker-adapter/issues/47), [#5](https://github.com/artipie/docker-adapter/issues/5) are still not solved; solved: [#10](https://github.com/artipie/docker-adapter/issues/10), [#11](https://github.com/artipie/docker-adapter/issues/11), [#12](https://github.com/artipie/docker-adapter/issues/12), [#13](https://github.com/artipie/docker-adapter/issues/13), [#17](https://github.com/artipie/docker-adapter/issues/17), [#19](https://github.com/artipie/docker-adapter/issues/19), [#25](https://github.com/artipie/docker-adapter/issues/25), [#2](https://github.com/artipie/docker-adapter/issues/2), [#36](https://github.com/artipie/docker-adapter/issues/36), [#41](https://github.com/artipie/docker-adapter/issues/41), [#43](https://github.com/artipie/docker-adapter/issues/43), [#6](https://github.com/artipie/docker-adapter/issues/6), [#7](https://github.com/artipie/docker-adapter/issues/7).

**Comment by 0pdd** [comment]
@g4s8 2 puzzles [#44](https://github.com/artipie/docker-adapter/issues/44), [#47](https://github.com/artipie/docker-adapter/issues/47) are still not solved; solved: [#10](https://github.com/artipie/docker-adapter/issues/10), [#11](https://github.com/artipie/docker-adapter/issues/11), [#12](https://github.com/artipie/docker-adapter/issues/12), [#13](https://github.com/artipie/docker-adapter/issues/13), [#17](https://github.com/artipie/docker-adapter/issues/17), [#19](https://github.com/artipie/docker-adapter/issues/19), [#25](https://github.com/artipie/docker-adapter/issues/25), [#2](https://github.com/artipie/docker-adapter/issues/2), [#36](https://github.com/artipie/docker-adapter/issues/36), [#41](https://github.com/artipie/docker-adapter/issues/41), [#43](https://github.com/artipie/docker-adapter/issues/43), [#5](https://github.com/artipie/docker-adapter/issues/5), [#6](https://github.com/artipie/docker-adapter/issues/6), [#7](https://github.com/artipie/docker-adapter/issues/7).

**Comment by 0pdd** [comment]
@g4s8 2 puzzles [#44](https://github.com/artipie/docker-adapter/issues/44), [#56](https://github.com/artipie/docker-adapter/issues/56) are still not solved; solved: [#10](https://github.com/artipie/docker-adapter/issues/10), [#11](https://github.com/artipie/docker-adapter/issues/11), [#12](https://github.com/artipie/docker-adapter/issues/12), [#13](https://github.com/artipie/docker-adapter/issues/13), [#17](https://github.com/artipie/docker-adapter/issues/17), [#19](https://github.com/artipie/docker-adapter/issues/19), [#25](https://github.com/artipie/docker-adapter/issues/25), [#2](https://github.com/artipie/docker-adapter/issues/2), [#36](https://github.com/artipie/docker-adapter/issues/36), [#41](https://github.com/artipie/docker-adapter/issues/41), [#43](https://github.com/artipie/docker-adapter/issues/43), [#47](https://github.com/artipie/docker-adapter/issues/47), [#5](https://github.com/artipie/docker-adapter/issues/5), [#6](https://github.com/artipie/docker-adapter/issues/6), [#7](https://github.com/artipie/docker-adapter/issues/7).

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#44](https://github.com/artipie/docker-adapter/issues/44) is still not solved; solved: [#10](https://github.com/artipie/docker-adapter/issues/10), [#11](https://github.com/artipie/docker-adapter/issues/11), [#12](https://github.com/artipie/docker-adapter/issues/12), [#13](https://github.com/artipie/docker-adapter/issues/13), [#17](https://github.com/artipie/docker-adapter/issues/17), [#19](https://github.com/artipie/docker-adapter/issues/19), [#25](https://github.com/artipie/docker-adapter/issues/25), [#2](https://github.com/artipie/docker-adapter/issues/2), [#36](https://github.com/artipie/docker-adapter/issues/36), [#41](https://github.com/artipie/docker-adapter/issues/41), [#43](https://github.com/artipie/docker-adapter/issues/43), [#47](https://github.com/artipie/docker-adapter/issues/47), [#56](https://github.com/artipie/docker-adapter/issues/56), [#5](https://github.com/artipie/docker-adapter/issues/5), [#6](https://github.com/artipie/docker-adapter/issues/6), [#7](https://github.com/artipie/docker-adapter/issues/7).

**Comment by 0pdd** [comment]
@g4s8 all 17 puzzles are solved here: [#10](https://github.com/artipie/docker-adapter/issues/10), [#11](https://github.com/artipie/docker-adapter/issues/11), [#12](https://github.com/artipie/docker-adapter/issues/12), [#13](https://github.com/artipie/docker-adapter/issues/13), [#17](https://github.com/artipie/docker-adapter/issues/17), [#19](https://github.com/artipie/docker-adapter/issues/19), [#25](https://github.com/artipie/docker-adapter/issues/25), [#2](https://github.com/artipie/docker-adapter/issues/2), [#36](https://github.com/artipie/docker-adapter/issues/36), [#41](https://github.com/artipie/docker-adapter/issues/41), [#43](https://github.com/artipie/docker-adapter/issues/43), [#44](https://github.com/artipie/docker-adapter/issues/44), [#47](https://github.com/artipie/docker-adapter/issues/47), [#56](https://github.com/artipie/docker-adapter/issues/56), [#5](https://github.com/artipie/docker-adapter/issues/5), [#6](https://github.com/artipie/docker-adapter/issues/6), [#7](https://github.com/artipie/docker-adapter/issues/7).
