### ISSUE TITLE
BlobStore.java:33-36: Add put method which should put new...

### ISSUE THREAD

**Issue by 0pdd** [artipie/docker-adapter#10]
The puzzle `6-b273da77` from #6 has to be resolved: 

https://github.com/artipie/docker-adapter/blob/f8266cb7546422b05e9c344d093494a370a9e1ba/src/main/java/com/artipie/docker/storage/BlobStore.java#L33-L36

The puzzle was created by @g4s8 on 17-Jan-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
The puzzle `6-b273da77` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job `gh:artipie/docker-adapter#10` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
