### ISSUE TITLE
AstoBlobs.java:34-37: Wait for new asto lib release and...

### ISSUE THREAD

**Issue by 0pdd** [artipie/docker-adapter#11]
The puzzle `6-613c2c91` from #6 has to be resolved: 

https://github.com/artipie/docker-adapter/blob/f8266cb7546422b05e9c344d093494a370a9e1ba/src/main/java/com/artipie/docker/storage/AstoBlobs.java#L34-L37

The puzzle was created by @g4s8 on 17-Jan-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
The job [#11](https://github.com/artipie/docker-adapter/issues/11) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/8b64bd69-2865-4581-b63f-39fcb44875ef); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Job `gh:artipie/docker-adapter#11` already assigned to @g4s8, can't assign to @g4s8

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) I see that you unassigned this issue; the order is still assigned to @g4s8[/z](https://www.0crat.com/u/g4s8) though; to cancel the order use `refuse`, as in [§6](http://www.zerocracy.com/policy.html#6)

**Comment by 0crat** [comment]
Job [#11](https://github.com/artipie/docker-adapter/issues/11) is already assigned to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0pdd** [comment]
The puzzle `6-613c2c91` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#36](https://github.com/artipie/docker-adapter/issues/36) is still not solved.

**Comment by 0crat** [comment]
Job was finished in 3 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#11](https://github.com/artipie/docker-adapter/issues/11) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0pdd** [comment]
@0pdd the puzzle [#41](https://github.com/artipie/docker-adapter/issues/41) is still not solved; solved: [#36](https://github.com/artipie/docker-adapter/issues/36).

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#43](https://github.com/artipie/docker-adapter/issues/43), [#44](https://github.com/artipie/docker-adapter/issues/44) are still not solved; solved: [#36](https://github.com/artipie/docker-adapter/issues/36), [#41](https://github.com/artipie/docker-adapter/issues/41).

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#44](https://github.com/artipie/docker-adapter/issues/44), [#47](https://github.com/artipie/docker-adapter/issues/47) are still not solved; solved: [#36](https://github.com/artipie/docker-adapter/issues/36), [#41](https://github.com/artipie/docker-adapter/issues/41), [#43](https://github.com/artipie/docker-adapter/issues/43).

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#44](https://github.com/artipie/docker-adapter/issues/44), [#56](https://github.com/artipie/docker-adapter/issues/56) are still not solved; solved: [#36](https://github.com/artipie/docker-adapter/issues/36), [#41](https://github.com/artipie/docker-adapter/issues/41), [#43](https://github.com/artipie/docker-adapter/issues/43), [#47](https://github.com/artipie/docker-adapter/issues/47).

**Comment by 0pdd** [comment]
@0pdd the puzzle [#44](https://github.com/artipie/docker-adapter/issues/44) is still not solved; solved: [#36](https://github.com/artipie/docker-adapter/issues/36), [#41](https://github.com/artipie/docker-adapter/issues/41), [#43](https://github.com/artipie/docker-adapter/issues/43), [#47](https://github.com/artipie/docker-adapter/issues/47), [#56](https://github.com/artipie/docker-adapter/issues/56).

**Comment by 0pdd** [comment]
@0pdd all 6 puzzles are solved here: [#36](https://github.com/artipie/docker-adapter/issues/36), [#41](https://github.com/artipie/docker-adapter/issues/41), [#43](https://github.com/artipie/docker-adapter/issues/43), [#44](https://github.com/artipie/docker-adapter/issues/44), [#47](https://github.com/artipie/docker-adapter/issues/47), [#56](https://github.com/artipie/docker-adapter/issues/56).
