### ISSUE TITLE
Error response body

### ISSUE THREAD

**Issue by olegmoz** [artipie/docker-adapter#117]
Docker registry is expected to respond with certain error descriptions when problems occur. Right now error responses such as invalid digest, blob not found etc are served with empty bodies.
See docs fro proper error reporting fromat: https://docs.docker.com/registry/spec/api/#errors and https://docs.docker.com/registry/spec/api/#errors-2

Example of `UNAUTHROZIED` error response from `https://registry-1.docker.io/v2/`:
```
{"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":null}]}
```

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#117](https://github.com/artipie/docker-adapter/issues/117) assigned to @artemlazarev[/z](https://www.0crat.com/u/artemlazarev), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/a1ff84c6-70f1-49d6-8c3b-8e430b97c6ba); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @artemlazarev[/z](https://www.0crat.com/u/artemlazarev) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job

**Comment by 0crat** [comment]
I'm not managing `artipie/docker-adapter` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)

**Comment by olegmoz** [comment]
@rultor release, tag=`0.4.1`
