### ISSUE TITLE
Temporary file usage in `AstoBlobs`

### ISSUE THREAD

**Issue by olegmoz** [artipie/docker-adapter#121]
`AstoBlobs.put()` implementation is using temporary file on local file system to write binary content before putting it into the storage. It is not required when blobs are small and fit in memory (manifests) or created from an upload (all other blobs, possibly large ones).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#121](https://github.com/artipie/docker-adapter/issues/121) assigned to @ilyamoskva[/z](https://www.0crat.com/u/ilyamoskva), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/f001564e-5f90-4803-9a8a-69464e1d9ac0); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @ilyamoskva[/z](https://www.0crat.com/u/ilyamoskva) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job

**Comment by olegmoz** [comment]
The issue is related to #157

**Comment by 0crat** [comment]
I'm not managing `artipie/docker-adapter` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@0cf2aef6-3274-4e83-b020-be89b679901f, thread: pool-1650-thread-1
com.zerocracy.radars.github.ThrottledComments[74] java.lang.IllegalStateException: Can't post an identical message to artipie/docker-adapter#121: I'm not managing `artipie/docker-adapter` GitHub repository, you have to contact me in Slack first, 
```

[0.53.15](https://github.com/zerocracy/farm): Issue: artipie/docker-adapter#121, Action: `unassigned`

**Comment by olegmoz** [comment]
@olenagerasimova this issue is quite important, could you please take on it in coming days?

**Comment by olenagerasimova** [comment]
@olegmoz I've missed this issue, sorry. Please check #236

**Comment by 0crat** [comment]
I'm not managing `artipie/docker-adapter` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)
