### ISSUE TITLE
Use Jacoco plugin settings from parent pom

### ISSUE THREAD

**Issue by olegmoz** [artipie/docker-adapter#122]
`ppom`  verion `0.3.3` now contains reference Jacoco plugin configuration, it should be used in the projec

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
Job `gh:artipie/docker-adapter#122` is not assigned, can't get performer
