### ISSUE TITLE
ManifestEntity.java:287-290: Manifest GET and HEAD...

### ISSUE THREAD

**Issue by 0pdd** [artipie/docker-adapter#128]
The puzzle `119-43b85444` from #119 has to be resolved: 

https://github.com/artipie/docker-adapter/blob/942d4e6ac5972ec0bf138fa608117d912f9bbc27/src/main/java/com/artipie/docker/http/ManifestEntity.java#L287-L290

The puzzle was created by @olenagerasimova on 19-May-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
I'm not managing `artipie/docker-adapter` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@e3dc009d-468d-4f7d-bd9f-6a9411479eb6, thread: pool-908-thread-1
com.zerocracy.radars.github.ThrottledComments[74] java.lang.IllegalStateException: Can't post an identical message to artipie/docker-adapter#128: I'm not managing `artipie/docker-adapter` GitHub repository, you have to contact me in Slack first, 
```

[0.53.15](https://github.com/zerocracy/farm): Issue: artipie/docker-adapter#128, Action: `closed`

**Comment by olegmoz** [comment]
@olenagerasimova could you please close the issue?
