### ISSUE TITLE
DockerSliceITCase.java:51-54: Support tests running on...

### ISSUE THREAD

**Issue by 0pdd** [artipie/docker-adapter#131]
The puzzle `54-6a79b312` from #54 has to be resolved: 

https://github.com/artipie/docker-adapter/blob/ad0ab140dcef82da0f6dc2815b86422f8cd756d3/src/test/java/com/artipie/docker/http/DockerSliceITCase.java#L51-L54

The puzzle was created by @olegmoz on 18-May-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
I'm not managing `artipie/docker-adapter` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)

**Comment by 0pdd** [comment]
@0pdd the puzzle [#154](https://github.com/artipie/docker-adapter/issues/154) is still not solved.

**Comment by 0crat** [comment]
I'm not managing `artipie/docker-adapter` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)

**Comment by olegmoz** [comment]
@rultor release, tag=`0.2`

**Comment by g4s8** [comment]
@rultor release, tag=`0.2`

**Comment by g4s8** [comment]
@rultor release, tag=`0.2`

**Comment by olegmoz** [comment]
@rultor release, tag=`0.2`

**Comment by olegmoz** [comment]
@g4s8 the release is failing now for some other reason, could you please have a look at it?

**Comment by g4s8** [comment]
@olegmoz there are some test failures:
```
[1;31mERRORm] com.artipie.docker.http.DockerSliceITCase.shouldPushExisting  Time elapsed: 0.161 s  <<< ERROR!
java.lang.IllegalStateException: Not OK exit code: 1
        at com.artipie.docker.http.DockerSliceITCase.run(DockerSliceITCase.java:177)
        at com.artipie.docker.http.DockerSliceITCase.prepare(DockerSliceITCase.java:239)
        at com.artipie.docker.http.DockerSliceITCase.linuxImage(DockerSliceITCase.java:225)
        at com.artipie.docker.http.DockerSliceITCase.prepareImage(DockerSliceITCase.java:194)
        at com.artipie.docker.http.DockerSliceITCase.setUp(DockerSliceITCase.java:96)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
```

Do you know why it failed?

**Comment by olegmoz** [comment]
@g4s8 this is docker client failure to pull an image from Docker Registry, here is the reason:
```
[2;37mDEBUGm] main com.artipie.docker.http.DockerSliceITCase: Command:
docker pull busybox@sha256:a7766145a775d39e53a713c75b6fd6d318740e70327aaa3ed5d09e0ef33fc3df
[2;37mDEBUGm] main com.artipie.docker.http.DockerSliceITCase: Full stdout/stderr:
Warning: failed to get default registry endpoint from daemon (Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.38/info: dial unix /var/run/docker.sock: connect: permission denied). Using system default: https://index.docker.io/v1/
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.38/images/create?fromImage=busybox&tag=sha256%3Aa7766145a775d39e53a713c75b6fd6d318740e70327aaa3ed5d09e0ef33fc3df: dial unix /var/run/docker.sock: connect: permission denied
```
No idea what does it mean, may we just disable integration tests on release?

**Comment by g4s8** [comment]
@olegmoz yes, I think we can disable it here

**Comment by olegmoz** [comment]
@rultor release, tag=`0.2`

**Comment by olegmoz** [comment]
@g4s8 could you please take a look at this error?

**Comment by olegmoz** [comment]
@rultor release, tag=`0.2`

**Comment by 0pdd** [comment]
@0pdd the only puzzle [#154](https://github.com/artipie/docker-adapter/issues/154) is solved here.
