### ISSUE TITLE
Upload start and existence check

### ISSUE THREAD

**Issue by olegmoz** [artipie/docker-adapter#136]
Upload entity is explicitly started by client using POST request and other operations are supposed to return 404 response in case upload has not been started yet.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
You @olegmoz[/z](https://www.0crat.com/u/olegmoz) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project

**Comment by 0crat** [comment]
I'm not managing `artipie/docker-adapter` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)
