### ISSUE TITLE
Support upload DELETE request

### ISSUE THREAD

**Issue by olegmoz** [artipie/docker-adapter#138]
Docker registry is supposed to delete uncomplete uploads by DELETE request, see https://docs.docker.com/registry/spec/api/#blob-upload

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
I'm not managing `artipie/docker-adapter` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)

**Comment by g4s8** [comment]
@brastak please check this ticket

**Comment by 0crat** [comment]
I'm not managing `artipie/docker-adapter` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@cc4a991f-2993-4061-849c-be39b0f7623a, thread: pool-1051-thread-1
com.zerocracy.radars.github.ThrottledComments[74] java.lang.IllegalStateException: Can't post an identical message to artipie/docker-adapter#138: I'm not managing `artipie/docker-adapter` GitHub repository, you have to contact me in Slack first, 
```

[0.53.15](https://github.com/zerocracy/farm): Issue: artipie/docker-adapter#138, Action: `unassigned`

**Comment by 0crat** [comment]
I'm not managing `artipie/docker-adapter` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)

**Comment by andreoss** [comment]
@g4s8 Please close, it's done in #502
