### ISSUE TITLE
UploadEntity.java:133-135: Compare digests before...

### ISSUE THREAD

**Issue by 0pdd** [artipie/docker-adapter#142]
The puzzle `137-db8c6c2a` from #137 has to be resolved: 

https://github.com/artipie/docker-adapter/blob/5a4e614f25ab9db64be76f94bf3f40c8f9947898/src/main/java/com/artipie/docker/http/UploadEntity.java#L133-L135

The puzzle was created by @olenagerasimova on 25-May-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
I'm not managing `artipie/docker-adapter` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)

**Comment by 0crat** [comment]
@0pdd[/z](https://www.0crat.com/u/0pdd) I'm not managing this repo, remove the [webhook](https://github.com/artipie/docker-adapter/settings/hooks) or contact me in Slack, as explained in [§11](http://www.zerocracy.com/policy.html#11); I'm not managing `artipie/docker-adapter` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11) /cc @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
I'm not managing `artipie/docker-adapter` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)

**Comment by 0pdd** [comment]
The puzzle `137-db8c6c2a` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#157](https://github.com/artipie/docker-adapter/issues/157), [#158](https://github.com/artipie/docker-adapter/issues/158) are still not solved.

**Comment by 0crat** [comment]
I'm not managing `artipie/docker-adapter` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#157](https://github.com/artipie/docker-adapter/issues/157), [#175](https://github.com/artipie/docker-adapter/issues/175) are still not solved; solved: [#158](https://github.com/artipie/docker-adapter/issues/158).

**Comment by 0pdd** [comment]
@0pdd the puzzle [#157](https://github.com/artipie/docker-adapter/issues/157) is still not solved; solved: [#158](https://github.com/artipie/docker-adapter/issues/158), [#175](https://github.com/artipie/docker-adapter/issues/175).

**Comment by 0pdd** [comment]
@0pdd all 3 puzzles are solved here: [#157](https://github.com/artipie/docker-adapter/issues/157), [#158](https://github.com/artipie/docker-adapter/issues/158), [#175](https://github.com/artipie/docker-adapter/issues/175).
