### ISSUE TITLE
Figure out whether should uploaded data be removed if digests do not match

### ISSUE THREAD

**Issue by 0pdd** [artipie/docker-adapter#143]
The puzzle `137-58fcdac8` from #137 has to be resolved: 

https://github.com/artipie/docker-adapter/blob/5a4e614f25ab9db64be76f94bf3f40c8f9947898/src/main/java/com/artipie/docker/http/UploadEntity.java#L136-L138

The puzzle was created by @olenagerasimova on 25-May-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
I'm not managing `artipie/docker-adapter` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)

**Comment by 0crat** [comment]
@0pdd[/z](https://www.0crat.com/u/0pdd) I'm not managing this repo, remove the [webhook](https://github.com/artipie/docker-adapter/settings/hooks) or contact me in Slack, as explained in [§11](http://www.zerocracy.com/policy.html#11); I'm not managing `artipie/docker-adapter` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11) /cc @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
I'm not managing `artipie/docker-adapter` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)

**Comment by dgarus** [comment]
@artipie/maintainers 
Hello!

The case when provided digest did not match uploaded content 
has the same effect as if we delete uploading. 
So I think we should delete uploading and all data 
that related to it. 

What I did:
1. Initiate uplaod `POST /v2/<name>/blobs/uploads`
2. Check that the upload exists `GET  /v2/<name>/blobs/uploads/<UUID>_state=<state>`
3. Complete upload with a bad digest and get error with the code `DIGEST_INVALID`
4. Check the upload `GET  /v2/<name>/blobs/uploads/<UUID>_state=<state>`
and get **404**.

**Comment by g4s8** [comment]
@dgarus great, thanks. Please create a new ticket from your investigation or replace a current `todo` with new information.

**Comment by dgarus** [comment]
@g4s8 created #506.
