### ISSUE TITLE
Store upload start date

### ISSUE THREAD

**Issue by olegmoz** [artipie/docker-adapter#148]
Original docker registry stores upload start date in `startedat` file in format like `2020-05-19T12:58:11Z`. We also need to store upload start date so it will be possible to cleanup too old blob updates.

**Comment by 0crat** [comment]
@olegmoz[/z](https://www.0crat.com/u/olegmoz) I'm not managing this repo, remove the [webhook](https://github.com/artipie/docker-adapter/settings/hooks) or contact me in Slack, as explained in [§11](http://www.zerocracy.com/policy.html#11); I'm not managing `artipie/docker-adapter` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11) /cc @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by dgarus** [comment]
@g4s8 hi!
could you please have a look?
