### ISSUE TITLE
Create integration test for pushing image with big layers

### ISSUE THREAD

**Issue by olegmoz** [artipie/docker-adapter#152]
In practice layers of Docker images might be huge (hundreds of megabytes or even gigabytes) and we need to support pushing such images into Artipie. Docker client might use still unsupported features in this case. So we need to have integration test with Docker client uploading huge image to Artipie to see what features we are lacking and keep this functionality covered in future.

**Comment by 0crat** [comment]
@olegmoz[/z](https://www.0crat.com/u/olegmoz) I'm not managing this repo, remove the [webhook](https://github.com/artipie/docker-adapter/settings/hooks) or contact me in Slack, as explained in [§11](http://www.zerocracy.com/policy.html#11); I'm not managing `artipie/docker-adapter` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11) /cc @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
I'm not managing `artipie/docker-adapter` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)

**Comment by 0pdd** [comment]
@olegmoz the puzzle [#177](https://github.com/artipie/docker-adapter/issues/177) is still not solved.

**Comment by 0crat** [comment]
I'm not managing `artipie/docker-adapter` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)

**Comment by 0pdd** [comment]
@olegmoz the only puzzle [#177](https://github.com/artipie/docker-adapter/issues/177) is solved here.
