### ISSUE TITLE
DockerSliceITCase.java:50-53: Refactor DockerSliceITCase...

### ISSUE THREAD

**Issue by 0pdd** [artipie/docker-adapter#154]
The puzzle `131-58dea826` from #131 has to be resolved: 

https://github.com/artipie/docker-adapter/blob/40d1d10825601b9a1245cffeb7b855002ba85fc4/src/test/java/com/artipie/docker/http/DockerSliceITCase.java#L50-L53

The puzzle was created by @olegmoz on 28-May-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
I'm not managing `artipie/docker-adapter` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)

**Comment by 0crat** [comment]
@0pdd[/z](https://www.0crat.com/u/0pdd) I'm not managing this repo, remove the [webhook](https://github.com/artipie/docker-adapter/settings/hooks) or contact me in Slack, as explained in [§11](http://www.zerocracy.com/policy.html#11); I'm not managing `artipie/docker-adapter` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11) /cc @yegor256[/z](https://www.0crat.com/u/yegor256)
