### ISSUE TITLE
UploadEntity.java:157-160: Content is read twice while...

### ISSUE THREAD

**Issue by 0pdd** [artipie/docker-adapter#157]
The puzzle `142-cff40642` from #142 has to be resolved: 

https://github.com/artipie/docker-adapter/blob/318ef76f258f88fe9cb4f76b0a8100fcc7c324d6/src/main/java/com/artipie/docker/http/UploadEntity.java#L157-L160

The puzzle was created by @olenagerasimova on 27-May-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by olegmoz** [comment]
The issue is related to #121

**Comment by 0crat** [comment]
I'm not managing `artipie/docker-adapter` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)

**Comment by 0crat** [comment]
@0pdd[/z](https://www.0crat.com/u/0pdd) I'm not managing this repo, remove the [webhook](https://github.com/artipie/docker-adapter/settings/hooks) or contact me in Slack, as explained in [§11](http://www.zerocracy.com/policy.html#11); I'm not managing `artipie/docker-adapter` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11) /cc @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0pdd** [comment]
> @0pdd[/z](https://www.0crat.com/u/0pdd) I'm not managing this repo, remove the [webhook](https://git...

  I see you're talking to me, but I can't reply since I'm not a chat bot.

**Comment by olegmoz** [comment]
@olenagerasimova would you like to take on this issue?

**Comment by olenagerasimova** [comment]
@olegmoz yes, assign me please

**Comment by 0crat** [comment]
I'm not managing `artipie/docker-adapter` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)

**Comment by olegmoz** [comment]
@olenagerasimova will you have time for this issue this week?

**Comment by olenagerasimova** [comment]
@olegmoz yes, let me look through the code once more and I either submit PR or we discuss tomorrow during the meeting

**Comment by olenagerasimova** [comment]
@olegmoz I do not see easy way to fix it as `AstoLayers.put()` is now responsible for adding layer to repository and `Layers` has a lot of implementations. Do you have any suggestions?

**Comment by olegmoz** [comment]
@olenagerasimova I think that it may be implemented in `BlobStore.put()` - this is the only place where a blob is added to our storage. The digest might be calculated "on the go" as bytes are being sent to `Storage`. On completion signal the digest should be verified. If there is mismatch then completion signal is transformed to error and whole `save` operation is aborted as result (all `Storage` implementations support that: saving faulty `Publisher` creates no entry in `Storage`).

That would be ideal solution in my opinion, what do you think?

**Comment by olenagerasimova** [comment]
@olegmoz hm, you are suggesting to pass digest from request to `BlobStore.put()` instead of calculated content digest, right?

**Comment by olegmoz** [comment]
@olenagerasimova yes, that's right. Expected digest passed inside the method and compared with actual digest calculated from content.

**Comment by olenagerasimova** [comment]
@olegmoz ok, got it

**Comment by 0pdd** [comment]
The puzzle `142-cff40642` has disappeared from the source code, that's why I closed this issue.
