### ISSUE TITLE
UploadEntity.java:235-237: Introduce separate class from...

### ISSUE THREAD

**Issue by 0pdd** [artipie/docker-adapter#158]
The puzzle `142-180677f0` from #142 has to be resolved: 

https://github.com/artipie/docker-adapter/blob/318ef76f258f88fe9cb4f76b0a8100fcc7c324d6/src/main/java/com/artipie/docker/http/UploadEntity.java#L235-L237

The puzzle was created by @olenagerasimova on 27-May-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
I'm not managing `artipie/docker-adapter` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)

**Comment by 0crat** [comment]
@0pdd[/z](https://www.0crat.com/u/0pdd) I'm not managing this repo, remove the [webhook](https://github.com/artipie/docker-adapter/settings/hooks) or contact me in Slack, as explained in [§11](http://www.zerocracy.com/policy.html#11); I'm not managing `artipie/docker-adapter` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11) /cc @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0pdd** [comment]
> @0pdd[/z](https://www.0crat.com/u/0pdd) I'm not managing this repo, remove the [webhook](https://git...

  I see you're talking to me, but I can't reply since I'm not a chat bot.

**Comment by 0crat** [comment]
I'm not managing `artipie/docker-adapter` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)

**Comment by olenagerasimova** [comment]
@olegmoz please, could you explain to me, why in `ManifestEntity.Put` we firstly obtain bytes from `body` and only then pass these bytes to blob store through publisher? Why `Content` instance is not simply created from request `body` to call `AstoBlobs#put`?

**Comment by olegmoz** [comment]
@olenagerasimova we do so because we need to parse and validate manifest content before saving. Manifests are not expected to be too big, so they should fit in memory.

**Comment by 0pdd** [comment]
The puzzle `142-180677f0` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#175](https://github.com/artipie/docker-adapter/issues/175) is still not solved.

**Comment by 0crat** [comment]
I'm not managing `artipie/docker-adapter` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)

**Comment by 0pdd** [comment]
@0pdd the only puzzle [#175](https://github.com/artipie/docker-adapter/issues/175) is solved here.
