### ISSUE TITLE
UploadEnitity.put.digest loads all layer content into the memory

### ISSUE THREAD

**Issue by brastak** [artipie/docker-adapter#163]
Docker layers can be really huge. `UploadEnitity.put.digest` method loads all content into the memory to calculate Sha256. Event for 128 megabytes layer it takes > 3 minutes.

**Comment by 0crat** [comment]
@brastak[/z](https://www.0crat.com/u/brastak) I'm not managing this repo, remove the [webhook](https://github.com/artipie/docker-adapter/settings/hooks) or contact me in Slack, as explained in [§11](http://www.zerocracy.com/policy.html#11); I'm not managing `artipie/docker-adapter` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11) /cc @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
I'm not managing `artipie/docker-adapter` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@d949d877-ee9b-4ca2-8884-b3e8d426e8d1, thread: pool-807-thread-1
com.zerocracy.radars.github.ThrottledComments[74] java.lang.IllegalStateException: Can't post an identical message to artipie/docker-adapter#163: I'm not managing `artipie/docker-adapter` GitHub repository, you have to contact me in Slack first, 
```

[0.53.15](https://github.com/zerocracy/farm): Issue: artipie/docker-adapter#163, Action: `closed`

**Comment by brastak** [comment]
Already fixed
