### ISSUE TITLE
Access layers via `Repo` instead of `BlobStore` in slices

### ISSUE THREAD

**Issue by olegmoz** [artipie/docker-adapter#167]
Part of #160 
`BlobStore` should not be exposed from Docker instance. Read and write layer operations should be done via `Repo` instead of direct access to `BlobStore`

**Comment by 0crat** [comment]
@olegmoz[/z](https://www.0crat.com/u/olegmoz) I'm not managing this repo, remove the [webhook](https://github.com/artipie/docker-adapter/settings/hooks) or contact me in Slack, as explained in [§11](http://www.zerocracy.com/policy.html#11); I'm not managing `artipie/docker-adapter` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11) /cc @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
I'm not managing `artipie/docker-adapter` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)

**Comment by 0pdd** [comment]
@olegmoz the puzzle [#194](https://github.com/artipie/docker-adapter/issues/194) is still not solved.

**Comment by 0crat** [comment]
I'm not managing `artipie/docker-adapter` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)

**Comment by 0pdd** [comment]
@olegmoz the only puzzle [#194](https://github.com/artipie/docker-adapter/issues/194) is solved here.
