### ISSUE TITLE
Manifest should be added as `Content` instead of `Blob` in `AstoRepo`

### ISSUE THREAD

**Issue by olegmoz** [artipie/docker-adapter#168]
Part of #160
Manifest should be added as `Content` instead of `Blob` in `AstoRepo` because `Manifests` might come from proxy and not be stored as blob at first.

**Comment by 0crat** [comment]
@olegmoz[/z](https://www.0crat.com/u/olegmoz) I'm not managing this repo, remove the [webhook](https://github.com/artipie/docker-adapter/settings/hooks) or contact me in Slack, as explained in [§11](http://www.zerocracy.com/policy.html#11); I'm not managing `artipie/docker-adapter` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11) /cc @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
I'm not managing `artipie/docker-adapter` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)

**Comment by 0pdd** [comment]
@olegmoz the puzzle [#176](https://github.com/artipie/docker-adapter/issues/176) is still not solved.

**Comment by 0crat** [comment]
I'm not managing `artipie/docker-adapter` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)

**Comment by 0pdd** [comment]
@olegmoz the puzzle [#182](https://github.com/artipie/docker-adapter/issues/182) is still not solved; solved: [#176](https://github.com/artipie/docker-adapter/issues/176).

**Comment by 0pdd** [comment]
@olegmoz all 2 puzzles are solved here: [#176](https://github.com/artipie/docker-adapter/issues/176), [#182](https://github.com/artipie/docker-adapter/issues/182).
