### ISSUE TITLE
Split `Repo` methods into `Manifests`, `Layers` and `Uploads`

### ISSUE THREAD

**Issue by olegmoz** [artipie/docker-adapter#169]
Part of #160
`Repo` class became too big, it could be split into into `Manifests`, `Layers` and `Uploads` with create/get methods

**Comment by 0crat** [comment]
@olegmoz[/z](https://www.0crat.com/u/olegmoz) I'm not managing this repo, remove the [webhook](https://github.com/artipie/docker-adapter/settings/hooks) or contact me in Slack, as explained in [§11](http://www.zerocracy.com/policy.html#11); I'm not managing `artipie/docker-adapter` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11) /cc @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
I'm not managing `artipie/docker-adapter` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)

**Comment by 0pdd** [comment]
@olegmoz the puzzle [#199](https://github.com/artipie/docker-adapter/issues/199) is still not solved.

**Comment by 0crat** [comment]
I'm not managing `artipie/docker-adapter` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)

**Comment by 0pdd** [comment]
@olegmoz the only puzzle [#199](https://github.com/artipie/docker-adapter/issues/199) is solved here.
