### ISSUE TITLE
Implement read only proxy `Docker`

### ISSUE THREAD

**Issue by olegmoz** [artipie/docker-adapter#170]
Part of #160
`ProxyDocker` should delegate all calls to remote repo configured by URL.
Authentication support is not part of this issue.

**Comment by 0crat** [comment]
@olegmoz[/z](https://www.0crat.com/u/olegmoz) I'm not managing this repo, remove the [webhook](https://github.com/artipie/docker-adapter/settings/hooks) or contact me in Slack, as explained in [§11](http://www.zerocracy.com/policy.html#11); I'm not managing `artipie/docker-adapter` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11) /cc @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
I'm not managing `artipie/docker-adapter` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)

**Comment by 0pdd** [comment]
@olegmoz the puzzle [#216](https://github.com/artipie/docker-adapter/issues/216) is still not solved.

**Comment by 0pdd** [comment]
@olegmoz 2 puzzles [#216](https://github.com/artipie/docker-adapter/issues/216), [#225](https://github.com/artipie/docker-adapter/issues/225) are still not solved.

**Comment by 0pdd** [comment]
@olegmoz 3 puzzles [#216](https://github.com/artipie/docker-adapter/issues/216), [#225](https://github.com/artipie/docker-adapter/issues/225), [#226](https://github.com/artipie/docker-adapter/issues/226) are still not solved.

**Comment by 0pdd** [comment]
@olegmoz 4 puzzles [#216](https://github.com/artipie/docker-adapter/issues/216), [#225](https://github.com/artipie/docker-adapter/issues/225), [#226](https://github.com/artipie/docker-adapter/issues/226), [#231](https://github.com/artipie/docker-adapter/issues/231) are still not solved.

**Comment by 0crat** [comment]
I'm not managing `artipie/docker-adapter` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)

**Comment by 0pdd** [comment]
@olegmoz 3 puzzles [#216](https://github.com/artipie/docker-adapter/issues/216), [#225](https://github.com/artipie/docker-adapter/issues/225), [#231](https://github.com/artipie/docker-adapter/issues/231) are still not solved; solved: [#226](https://github.com/artipie/docker-adapter/issues/226).

**Comment by 0pdd** [comment]
@olegmoz 2 puzzles [#216](https://github.com/artipie/docker-adapter/issues/216), [#225](https://github.com/artipie/docker-adapter/issues/225) are still not solved; solved: [#226](https://github.com/artipie/docker-adapter/issues/226), [#231](https://github.com/artipie/docker-adapter/issues/231).

**Comment by olegmoz** [comment]
@rultor release, tag=`0.2.6`

**Comment by 0pdd** [comment]
@olegmoz the puzzle [#216](https://github.com/artipie/docker-adapter/issues/216) is still not solved; solved: [#225](https://github.com/artipie/docker-adapter/issues/225), [#226](https://github.com/artipie/docker-adapter/issues/226), [#231](https://github.com/artipie/docker-adapter/issues/231).

**Comment by 0pdd** [comment]
@olegmoz all 4 puzzles are solved here: [#216](https://github.com/artipie/docker-adapter/issues/216), [#225](https://github.com/artipie/docker-adapter/issues/225), [#226](https://github.com/artipie/docker-adapter/issues/226), [#231](https://github.com/artipie/docker-adapter/issues/231).
