### ISSUE TITLE
Implement multi-remote `Docker`

### ISSUE THREAD

**Issue by olegmoz** [artipie/docker-adapter#173]
Part of #160 
Multi-remote `Docker` implementation should accept list of proxy dockers and forward request to them.
List of proxies should be ordered so user could specify remotes' priorities.

**Comment by 0crat** [comment]
@olegmoz[/z](https://www.0crat.com/u/olegmoz) I'm not managing this repo, remove the [webhook](https://github.com/artipie/docker-adapter/settings/hooks) or contact me in Slack, as explained in [§11](http://www.zerocracy.com/policy.html#11); I'm not managing `artipie/docker-adapter` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11) /cc @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
I'm not managing `artipie/docker-adapter` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)
