### ISSUE TITLE
UploadEntity.java:165-167: Digest is calculated twice...

### ISSUE THREAD

**Issue by 0pdd** [artipie/docker-adapter#175]
The puzzle `158-a4be373e` from #158 has to be resolved: 

https://github.com/artipie/docker-adapter/blob/22c36d746047c0773786969639dc5b264b93855f/src/main/java/com/artipie/docker/http/UploadEntity.java#L165-L167

The puzzle was created by @olenagerasimova on 02-Jun-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
I'm not managing `artipie/docker-adapter` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)

**Comment by olenagerasimova** [comment]
@olegmoz if you agree with adding `digest` parameter to `AstoBlobs#put()` to avoid double digest calculation, I'd take this issue

**Comment by olegmoz** [comment]
@olenagerasimova sure

**Comment by 0crat** [comment]
I'm not managing `artipie/docker-adapter` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)

**Comment by olegmoz** [comment]
@olenagerasimova please take a look at issue #121 it is closely related. When you will pass digest to `AstoBlobs.put` method there will be no reason to use a temporary file

**Comment by 0pdd** [comment]
The puzzle `158-a4be373e` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
I'm not managing `artipie/docker-adapter` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)
