### ISSUE TITLE
AstoRepo.java:53-58: Extract reading `Content` as byte...

### ISSUE THREAD

**Issue by 0pdd** [artipie/docker-adapter#176]
The puzzle `168-9682376c` from #168 has to be resolved: 

https://github.com/artipie/docker-adapter/blob/a04c6d92bd9ae27ba2db11bfc96b080b39d60c63/src/main/java/com/artipie/docker/asto/AstoRepo.java#L53-L58

The puzzle was created by @olegmoz on 03-Jun-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
I'm not managing `artipie/docker-adapter` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)

**Comment by 0crat** [comment]
@0pdd[/z](https://www.0crat.com/u/0pdd) I'm not managing this repo, remove the [webhook](https://github.com/artipie/docker-adapter/settings/hooks) or contact me in Slack, as explained in [§11](http://www.zerocracy.com/policy.html#11); I'm not managing `artipie/docker-adapter` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11) /cc @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
I'm not managing `artipie/docker-adapter` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)

**Comment by 0pdd** [comment]
The puzzle `168-9682376c` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#182](https://github.com/artipie/docker-adapter/issues/182) is still not solved.

**Comment by 0crat** [comment]
I'm not managing `artipie/docker-adapter` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)

**Comment by 0pdd** [comment]
@0pdd the only puzzle [#182](https://github.com/artipie/docker-adapter/issues/182) is solved here.
