### ISSUE TITLE
LargeImageITCase.java:50-51: min Extract common methods...

### ISSUE THREAD

**Issue by 0pdd** [artipie/docker-adapter#177]
The puzzle `152-d6e32dc9` from #152 has to be resolved: 

https://github.com/artipie/docker-adapter/blob/cb80aa8a77b7d97e8a9f1cadbc61dc443ad11a25/src/test/java/com/artipie/docker/http/LargeImageITCase.java#L50-L51

The puzzle was created by brastak on 29-May-20. 

Estimate: 45 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
I'm not managing `artipie/docker-adapter` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)

**Comment by olegmoz** [comment]
@brastak would you like to take on this issue?

**Comment by 0crat** [comment]
@0pdd[/z](https://www.0crat.com/u/0pdd) I'm not managing this repo, remove the [webhook](https://github.com/artipie/docker-adapter/settings/hooks) or contact me in Slack, as explained in [§11](http://www.zerocracy.com/policy.html#11); I'm not managing `artipie/docker-adapter` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11) /cc @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
I'm not managing `artipie/docker-adapter` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)

**Comment by brastak** [comment]
@olegmoz Yes, I will take it

**Comment by 0pdd** [comment]
The puzzle `152-d6e32dc9` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
I'm not managing `artipie/docker-adapter` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)
