### ISSUE TITLE
Unable to push docker image 500 error

### ISSUE THREAD

**Issue by g4s8** [artipie/docker-adapter#180]
I created Docker repository as described in Artipie [README](https://github.com/artipie/artipie#docker-repo) as `public/docker`:
```yaml
repo:
  type: docker
  path: public/docker
  permissions:
    \*:
      - \*
  storage:
    type: s3
```
And configured Nginx reverse proxy at `central.artipie.com` to rewrite all `/v2` URIs to `/public/docker`:
```nginx
rewrite ^(/v2/.*)$ /public/docker$1 last;
```

Then I tagged `alpine:3.10` with `docker tag alpine:3.10 central.artipie.com/alpine:3.10`

And pushed to this repository: `docker push central.artipie.com/alpine:3.10`

But Artipie failed with multiple 500 errors:
```
artipie    | [INFO] 2020-06-04 07:15:14,819 vert.x-eventloop-thread-1 com.artipie.Pie - Request: GET /public/docker/v2/ HTTP_1_0
nginx      | [04/Jun/2020:07:15:14 +0000] "GET /v2/ HTTP/1.1" 500
artipie    | [INFO] 2020-06-04 07:15:15,635 vert.x-eventloop-thread-1 com.artipie.Pie - Request: GET /public/docker/v2/artipie/manifests/0.1 HTTP_1_0
nginx      | [04/Jun/2020:07:15:15 +0000] "GET /v2/artipie/manifests/0.1 HTTP/1.1" 500
artipie    | [INFO] 2020-06-04 07:15:57,036 vert.x-eventloop-thread-1 com.artipie.Pie - Request: GET /public/docker/v2/ HTTP_1_0
nginx      | [04/Jun/2020:07:15:57 +0000] "GET /v2/ HTTP/1.1" 500
artipie    | [INFO] 2020-06-04 07:15:57,941 vert.x-eventloop-thread-1 com.artipie.Pie - Request: HEAD /public/docker/v2/alpine/blobs/sha256:89d9c30c1d48bac627e5c6cb0d1ed1eec28e7dbdfbcc04712e4c79c0f83faf17 HTTP_1_0
nginx      | [04/Jun/2020:07:15:57 +0000] "HEAD /v2/alpine/blobs/sha256:89d9c30c1d48bac627e5c6cb0d1ed1eec28e7dbdfbcc04712e4c79c0f83faf17 HTTP/1.1" 500
artipie    | [INFO] 2020-06-04 07:15:58,744 vert.x-eventloop-thread-1 com.artipie.Pie - Request: POST /public/docker/v2/alpine/blobs/uploads/ HTTP_1_0
nginx      | [04/Jun/2020:07:15:58 +0000] "POST /v2/alpine/blobs/uploads/ HTTP/1.1" 500
artipie    | [INFO] 2020-06-04 07:16:04,547 vert.x-eventloop-thread-1 com.artipie.Pie - Request: POST /public/docker/v2/alpine/blobs/uploads/ HTTP_1_0
nginx      | [04/Jun/2020:07:16:04 +0000] "POST /v2/alpine/blobs/uploads/ HTTP/1.1" 500
```

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) I'm not managing this repo, remove the [webhook](https://github.com/artipie/docker-adapter/settings/hooks) or contact me in Slack, as explained in [§11](http://www.zerocracy.com/policy.html#11); I'm not managing `artipie/docker-adapter` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11) /cc @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
I'm not managing `artipie/docker-adapter` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@d949d877-ee9b-4ca2-8884-b3e8d426e8d1, thread: pool-514-thread-1
com.zerocracy.radars.github.ThrottledComments[74] java.lang.IllegalStateException: Can't post an identical message to artipie/docker-adapter#180: I'm not managing `artipie/docker-adapter` GitHub repository, you have to contact me in Slack first, 
```

[0.53.15](https://github.com/zerocracy/farm): Issue: artipie/docker-adapter#180, Action: `assigned`

**Comment by olegmoz** [comment]
@g4s8 could you please try to change `path: public/docker` to `path: /public/docker` in your config?

**Comment by g4s8** [comment]
@olegmoz thanks, it solves the issue.

**Comment by 0crat** [comment]
I'm not managing `artipie/docker-adapter` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)
