### ISSUE TITLE
Blob, manifest and upload routes do not support multipart image names

### ISSUE THREAD

**Issue by olegmoz** [artipie/docker-adapter#189]
Docker image may consist of multiple parts separated by `/`, such as `dotnet/core/runtime`.
Blob, manifest and upload routes support only names without `/` symbol inside

**Comment by 0crat** [comment]
@olegmoz[/z](https://www.0crat.com/u/olegmoz) I'm not managing this repo, remove the [webhook](https://github.com/artipie/docker-adapter/settings/hooks) or contact me in Slack, as explained in [§11](http://www.zerocracy.com/policy.html#11); I'm not managing `artipie/docker-adapter` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11) /cc @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
I'm not managing `artipie/docker-adapter` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@be8f3153-53d6-4e50-b218-20848798df0e, thread: pool-499-thread-1
com.zerocracy.radars.github.ThrottledComments[74] java.lang.IllegalStateException: Can't post an identical message to artipie/docker-adapter#189: I'm not managing `artipie/docker-adapter` GitHub repository, you have to contact me in Slack first, 
```

[0.53.15](https://github.com/zerocracy/farm): Issue: artipie/docker-adapter#189, Action: `unassigned`

**Comment by 0crat** [comment]
I'm not managing `artipie/docker-adapter` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)

**Comment by olenagerasimova** [comment]
@olegmoz I'm afraid we need to discuss this, I do not have any ideas, do you?

**Comment by olegmoz** [comment]
@olenagerasimova I am pretty sure that this can be fixed just by replacing repo name pattern in RegEx expressions from `[^/]` to `.` and testing it. Maybe it is not as simple as that. I'd be gald to discuss this matter if there are any problems

**Comment by 0crat** [comment]
I'm not managing `artipie/docker-adapter` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)
