### ISSUE TITLE
AstoUploads.java:38-40: Add unit tests for `AstoUpload`...

### ISSUE THREAD

**Issue by 0pdd** [artipie/docker-adapter#199]
The puzzle `169-5fcdf6b9` from #169 has to be resolved: 

https://github.com/artipie/docker-adapter/blob/b5c921f01a579f02855a1299dab5e0982fca5a4e/src/main/java/com/artipie/docker/asto/AstoUploads.java#L38-L40

The puzzle was created by @olegmoz on 10-Jun-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
I'm not managing `artipie/docker-adapter` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)

**Comment by 0crat** [comment]
@0pdd[/z](https://www.0crat.com/u/0pdd) I'm not managing this repo, remove the [webhook](https://github.com/artipie/docker-adapter/settings/hooks) or contact me in Slack, as explained in [§11](http://www.zerocracy.com/policy.html#11); I'm not managing `artipie/docker-adapter` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11) /cc @yegor256[/z](https://www.0crat.com/u/yegor256)
