### ISSUE TITLE
Very slow matching of HTTP path by RegEx

### ISSUE THREAD

**Issue by olegmoz** [artipie/docker-adapter#206]
Looking at builds, such as https://github.com/artipie/docker-adapter/actions/runs/131395784 one may notice that tests involving matching HTTP request paths were very slow. This happens because recently introduced RegEx
```
public static final Pattern PATH = Pattern.compile(
        "^/v2/(?<name>([a-z0-9]+([._-]?[a-z0-9]+)*/?)+)/blobs/uploads/(?<uuid>.*)$"
    );
```
runs super slow on string like `/v2/my-repo/blobs/uploads/a9e48d2a-c939-441d-bb53-b3ad9ab67709`. This does not happen for strings like `/v2/my-repo/blobs/uploads/` or `/v2/my-repo/blobs/uploads/123-abc`.

**Comment by 0crat** [comment]
I'm not managing `artipie/docker-adapter` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)

**Comment by 0crat** [comment]
@olegmoz[/z](https://www.0crat.com/u/olegmoz) I'm not managing this repo, remove the [webhook](https://github.com/artipie/docker-adapter/settings/hooks) or contact me in Slack, as explained in [§11](http://www.zerocracy.com/policy.html#11); I'm not managing `artipie/docker-adapter` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11) /cc @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
I'm not managing `artipie/docker-adapter` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)
