### ISSUE TITLE
Virtual Docker repository

### ISSUE THREAD

**Issue by olegmoz** [artipie/docker-adapter#255]
Virtual Docker repository is expected to be combination on multiple proxy repositories and local repository. Read requests should be sent to both proxy and local repositories and write operations should go to local repository only.

Implementation may be done as composite `Docker` that has single `read` and `write` delegates. `read` delegate could be composed from proxy and local Docker after completing #173

**Comment by 0crat** [comment]
@olegmoz[/z](https://www.0crat.com/u/olegmoz) I'm not managing this repo, remove the [webhook](https://github.com/artipie/docker-adapter/settings/hooks) or contact me in Slack, as explained in [§11](http://www.zerocracy.com/policy.html#11); I'm not managing `artipie/docker-adapter` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11) /cc @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
I'm not managing `artipie/docker-adapter` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)

**Comment by 0pdd** [comment]
@olegmoz 2 puzzles [#268](https://github.com/artipie/docker-adapter/issues/268), [#269](https://github.com/artipie/docker-adapter/issues/269) are still not solved.

**Comment by 0pdd** [comment]
@olegmoz the puzzle [#269](https://github.com/artipie/docker-adapter/issues/269) is still not solved; solved: [#268](https://github.com/artipie/docker-adapter/issues/268).

**Comment by 0pdd** [comment]
@olegmoz all 2 puzzles are solved here: [#268](https://github.com/artipie/docker-adapter/issues/268), [#269](https://github.com/artipie/docker-adapter/issues/269).
