### ISSUE TITLE
Not properly formatted error responses

### ISSUE THREAD

**Issue by g4s8** [artipie/docker-adapter#260]
When I'm trying to `pull` docker image which doesn't exist on the server, Artipie responds with 404 status but it doesn't use special json messages:
```
$ docker pull central.artipie.com/g4s8/docker/alpine:3.9
Error response from daemon: error parsing HTTP 404 response body: unexpected end of JSON input: ""
```

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) I'm not managing this repo, remove the [webhook](https://github.com/artipie/docker-adapter/settings/hooks) or contact me in Slack, as explained in [§11](http://www.zerocracy.com/policy.html#11); I'm not managing `artipie/docker-adapter` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11) /cc @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
I'm not managing `artipie/docker-adapter` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@ceb75b72-5128-4a32-a6a0-db018bc785eb, thread: pool-777-thread-1
com.zerocracy.radars.github.ThrottledComments[74] java.lang.IllegalStateException: Can't post an identical message to artipie/docker-adapter#260: I'm not managing `artipie/docker-adapter` GitHub repository, you have to contact me in Slack first, 
```

[0.53.15](https://github.com/zerocracy/farm): Issue: artipie/docker-adapter#260, Action: `labeled`

**Comment by olegmoz** [comment]
@g4s8 thanks, this issue is known see #170 
Unfortunately it has quite long and complicated history. I will try to address this issue soon

**Comment by g4s8** [comment]
@olegmoz got it, thanks.

**Comment by 0crat** [comment]
I'm not managing `artipie/docker-adapter` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)
