### ISSUE TITLE
Support prefix for repository names

### ISSUE THREAD

**Issue by olegmoz** [artipie/docker-adapter#263]
When there are multiple Docker registries hosted on same server they are distinguished by prefix of repository names, but might be stored in different storages. Docker adapter should support feature of prefixed repository names, so image with name like `g4s8/docker/alpine` would be stored as `alpine` if prefix is set to be `g4s8/docker`. This might be done as special implementation of `Docker` interface that cuts out prefix from repository name. This implementation should no allow image names not starting with prefix specified.

**Comment by olenagerasimova** [comment]
@olegmoz yes, assign me please

**Comment by olenagerasimova** [comment]
@olegmoz where this new `TrimmedDocker` should be used? Or there is another issue for it?

**Comment by olegmoz** [comment]
@rultor release, tag=`0.3.1`

**Comment by olegmoz** [comment]
@olenagerasimova I've created issue in Artipie about usage of this new class, see https://github.com/artipie/artipie/issues/371
