### ISSUE TITLE
Integration testing

### ISSUE THREAD

**Issue by g4s8** [artipie/docker-adapter#27]
Add integration tests with real Docker registry layout file. Use stubs instead of real layer blobs.

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#29](https://github.com/artipie/docker-adapter/issues/29) is still not solved.

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#31](https://github.com/artipie/docker-adapter/issues/31) is still not solved; solved: [#29](https://github.com/artipie/docker-adapter/issues/29).

**Comment by 0crat** [comment]
Job `gh:artipie/docker-adapter#27` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Comment by 0pdd** [comment]
@g4s8 all 2 puzzles are solved here: [#29](https://github.com/artipie/docker-adapter/issues/29), [#31](https://github.com/artipie/docker-adapter/issues/31).
