### ISSUE TITLE
Contribute to docker-java-api?

### ISSUE THREAD

**Issue by amihaiemil** [artipie/docker-adapter#3]
I already have an adapter for Docker's API. So far, it covers only parts of the Engine API, but we could continue working on it so it extends also the Registry API. 

Check it out: https://www.github.com/amihaiemil/docker-java-api

It's built using Apache HTTP Client.

**Comment by g4s8** [comment]
@amihaiemil thanks for suggestion, but the purpose of this repo is to create an abstraction layer for Docker registry files layout structure without using Docker itself. It will be used by binary repository aggregator, see: https://github.com/artipie/white-paper

**Comment by amihaiemil** [comment]
@g4s8 I see, thanks! I'm closing this :)
