### ISSUE TITLE
AstoRepoITCase.java:41-43: This test is failing. Manifest...

### ISSUE THREAD

**Issue by 0pdd** [artipie/docker-adapter#31]
The puzzle `29-bca8bfcb` from #29 has to be resolved: 

https://github.com/artipie/docker-adapter/blob/19ceb25d775f90cdb401bc039595f7f4b7af849d/src/test/java/com/artipie/docker/storage/AstoRepoITCase.java#L41-L43

The puzzle was created by @g4s8 on 23-Jan-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
The puzzle `29-bca8bfcb` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job `gh:artipie/docker-adapter#31` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
