### ISSUE TITLE
Image tags listing

### ISSUE THREAD

**Issue by olegmoz** [artipie/docker-adapter#354]
Docker should handle tags listing requests `GET /v2/<name>/tags/list?n=<count>last=<last page name>`, see https://docs.docker.com/registry/spec/api/#tags

**Comment by olegmoz** [comment]
@rultor release, tag=`0.7.2`

**Comment by 0pdd** [comment]
@olegmoz 11 puzzles [#366](https://github.com/artipie/docker-adapter/issues/366), [#367](https://github.com/artipie/docker-adapter/issues/367), [#368](https://github.com/artipie/docker-adapter/issues/368), [#369](https://github.com/artipie/docker-adapter/issues/369), [#370](https://github.com/artipie/docker-adapter/issues/370), [#371](https://github.com/artipie/docker-adapter/issues/371), [#372](https://github.com/artipie/docker-adapter/issues/372), [#373](https://github.com/artipie/docker-adapter/issues/373), [#374](https://github.com/artipie/docker-adapter/issues/374), [#375](https://github.com/artipie/docker-adapter/issues/375), [#376](https://github.com/artipie/docker-adapter/issues/376) are still not solved.

**Comment by 0pdd** [comment]
@olegmoz 10 puzzles [#366](https://github.com/artipie/docker-adapter/issues/366), [#367](https://github.com/artipie/docker-adapter/issues/367), [#368](https://github.com/artipie/docker-adapter/issues/368), [#369](https://github.com/artipie/docker-adapter/issues/369), [#370](https://github.com/artipie/docker-adapter/issues/370), [#371](https://github.com/artipie/docker-adapter/issues/371), [#372](https://github.com/artipie/docker-adapter/issues/372), [#374](https://github.com/artipie/docker-adapter/issues/374), [#375](https://github.com/artipie/docker-adapter/issues/375), [#376](https://github.com/artipie/docker-adapter/issues/376) are still not solved; solved: [#373](https://github.com/artipie/docker-adapter/issues/373).

**Comment by 0pdd** [comment]
@olegmoz 9 puzzles [#366](https://github.com/artipie/docker-adapter/issues/366), [#367](https://github.com/artipie/docker-adapter/issues/367), [#368](https://github.com/artipie/docker-adapter/issues/368), [#369](https://github.com/artipie/docker-adapter/issues/369), [#370](https://github.com/artipie/docker-adapter/issues/370), [#371](https://github.com/artipie/docker-adapter/issues/371), [#372](https://github.com/artipie/docker-adapter/issues/372), [#374](https://github.com/artipie/docker-adapter/issues/374), [#375](https://github.com/artipie/docker-adapter/issues/375) are still not solved; solved: [#373](https://github.com/artipie/docker-adapter/issues/373), [#376](https://github.com/artipie/docker-adapter/issues/376).

**Comment by 0pdd** [comment]
@olegmoz 8 puzzles [#366](https://github.com/artipie/docker-adapter/issues/366), [#367](https://github.com/artipie/docker-adapter/issues/367), [#368](https://github.com/artipie/docker-adapter/issues/368), [#369](https://github.com/artipie/docker-adapter/issues/369), [#371](https://github.com/artipie/docker-adapter/issues/371), [#372](https://github.com/artipie/docker-adapter/issues/372), [#374](https://github.com/artipie/docker-adapter/issues/374), [#375](https://github.com/artipie/docker-adapter/issues/375) are still not solved; solved: [#370](https://github.com/artipie/docker-adapter/issues/370), [#373](https://github.com/artipie/docker-adapter/issues/373), [#376](https://github.com/artipie/docker-adapter/issues/376).

**Comment by 0pdd** [comment]
@olegmoz 7 puzzles [#366](https://github.com/artipie/docker-adapter/issues/366), [#367](https://github.com/artipie/docker-adapter/issues/367), [#368](https://github.com/artipie/docker-adapter/issues/368), [#369](https://github.com/artipie/docker-adapter/issues/369), [#372](https://github.com/artipie/docker-adapter/issues/372), [#374](https://github.com/artipie/docker-adapter/issues/374), [#375](https://github.com/artipie/docker-adapter/issues/375) are still not solved; solved: [#370](https://github.com/artipie/docker-adapter/issues/370), [#371](https://github.com/artipie/docker-adapter/issues/371), [#373](https://github.com/artipie/docker-adapter/issues/373), [#376](https://github.com/artipie/docker-adapter/issues/376).

**Comment by 0pdd** [comment]
@olegmoz 6 puzzles [#366](https://github.com/artipie/docker-adapter/issues/366), [#367](https://github.com/artipie/docker-adapter/issues/367), [#369](https://github.com/artipie/docker-adapter/issues/369), [#372](https://github.com/artipie/docker-adapter/issues/372), [#374](https://github.com/artipie/docker-adapter/issues/374), [#375](https://github.com/artipie/docker-adapter/issues/375) are still not solved; solved: [#368](https://github.com/artipie/docker-adapter/issues/368), [#370](https://github.com/artipie/docker-adapter/issues/370), [#371](https://github.com/artipie/docker-adapter/issues/371), [#373](https://github.com/artipie/docker-adapter/issues/373), [#376](https://github.com/artipie/docker-adapter/issues/376).

**Comment by 0pdd** [comment]
@olegmoz 5 puzzles [#366](https://github.com/artipie/docker-adapter/issues/366), [#369](https://github.com/artipie/docker-adapter/issues/369), [#372](https://github.com/artipie/docker-adapter/issues/372), [#374](https://github.com/artipie/docker-adapter/issues/374), [#375](https://github.com/artipie/docker-adapter/issues/375) are still not solved; solved: [#367](https://github.com/artipie/docker-adapter/issues/367), [#368](https://github.com/artipie/docker-adapter/issues/368), [#370](https://github.com/artipie/docker-adapter/issues/370), [#371](https://github.com/artipie/docker-adapter/issues/371), [#373](https://github.com/artipie/docker-adapter/issues/373), [#376](https://github.com/artipie/docker-adapter/issues/376).

**Comment by 0pdd** [comment]
@olegmoz 4 puzzles [#366](https://github.com/artipie/docker-adapter/issues/366), [#369](https://github.com/artipie/docker-adapter/issues/369), [#372](https://github.com/artipie/docker-adapter/issues/372), [#374](https://github.com/artipie/docker-adapter/issues/374) are still not solved; solved: [#367](https://github.com/artipie/docker-adapter/issues/367), [#368](https://github.com/artipie/docker-adapter/issues/368), [#370](https://github.com/artipie/docker-adapter/issues/370), [#371](https://github.com/artipie/docker-adapter/issues/371), [#373](https://github.com/artipie/docker-adapter/issues/373), [#375](https://github.com/artipie/docker-adapter/issues/375), [#376](https://github.com/artipie/docker-adapter/issues/376).

**Comment by 0pdd** [comment]
@olegmoz 3 puzzles [#366](https://github.com/artipie/docker-adapter/issues/366), [#372](https://github.com/artipie/docker-adapter/issues/372), [#374](https://github.com/artipie/docker-adapter/issues/374) are still not solved; solved: [#367](https://github.com/artipie/docker-adapter/issues/367), [#368](https://github.com/artipie/docker-adapter/issues/368), [#369](https://github.com/artipie/docker-adapter/issues/369), [#370](https://github.com/artipie/docker-adapter/issues/370), [#371](https://github.com/artipie/docker-adapter/issues/371), [#373](https://github.com/artipie/docker-adapter/issues/373), [#375](https://github.com/artipie/docker-adapter/issues/375), [#376](https://github.com/artipie/docker-adapter/issues/376).

**Comment by 0pdd** [comment]
@olegmoz 2 puzzles [#372](https://github.com/artipie/docker-adapter/issues/372), [#374](https://github.com/artipie/docker-adapter/issues/374) are still not solved; solved: [#366](https://github.com/artipie/docker-adapter/issues/366), [#367](https://github.com/artipie/docker-adapter/issues/367), [#368](https://github.com/artipie/docker-adapter/issues/368), [#369](https://github.com/artipie/docker-adapter/issues/369), [#370](https://github.com/artipie/docker-adapter/issues/370), [#371](https://github.com/artipie/docker-adapter/issues/371), [#373](https://github.com/artipie/docker-adapter/issues/373), [#375](https://github.com/artipie/docker-adapter/issues/375), [#376](https://github.com/artipie/docker-adapter/issues/376).

**Comment by 0pdd** [comment]
@olegmoz the puzzle [#374](https://github.com/artipie/docker-adapter/issues/374) is still not solved; solved: [#366](https://github.com/artipie/docker-adapter/issues/366), [#367](https://github.com/artipie/docker-adapter/issues/367), [#368](https://github.com/artipie/docker-adapter/issues/368), [#369](https://github.com/artipie/docker-adapter/issues/369), [#370](https://github.com/artipie/docker-adapter/issues/370), [#371](https://github.com/artipie/docker-adapter/issues/371), [#372](https://github.com/artipie/docker-adapter/issues/372), [#373](https://github.com/artipie/docker-adapter/issues/373), [#375](https://github.com/artipie/docker-adapter/issues/375), [#376](https://github.com/artipie/docker-adapter/issues/376).

**Comment by olegmoz** [comment]
@rultor release, tag=`0.10`

**Comment by 0pdd** [comment]
@olegmoz all 11 puzzles are solved here: [#366](https://github.com/artipie/docker-adapter/issues/366), [#367](https://github.com/artipie/docker-adapter/issues/367), [#368](https://github.com/artipie/docker-adapter/issues/368), [#369](https://github.com/artipie/docker-adapter/issues/369), [#370](https://github.com/artipie/docker-adapter/issues/370), [#371](https://github.com/artipie/docker-adapter/issues/371), [#372](https://github.com/artipie/docker-adapter/issues/372), [#373](https://github.com/artipie/docker-adapter/issues/373), [#374](https://github.com/artipie/docker-adapter/issues/374), [#375](https://github.com/artipie/docker-adapter/issues/375), [#376](https://github.com/artipie/docker-adapter/issues/376).
