### ISSUE TITLE
AstoBlobs.java:37-40: Implement put() method. It should...

### ISSUE THREAD

**Issue by 0pdd** [artipie/docker-adapter#36]
The puzzle `11-8017f439` from #11 has to be resolved: 

https://github.com/artipie/docker-adapter/blob/407dad0982ebd0471b0d75a667be9a71c4d7d34b/src/main/java/com/artipie/docker/asto/AstoBlobs.java#L37-L40

The puzzle was created by @g4s8 on 27-Jan-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#36](https://github.com/artipie/docker-adapter/issues/36) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/b6529f73-12cb-4ead-97ee-264261b44a6b); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0pdd** [comment]
The puzzle `11-8017f439` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#41](https://github.com/artipie/docker-adapter/issues/41) is still not solved.

**Comment by 0crat** [comment]
Job was finished in 23 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#43](https://github.com/artipie/docker-adapter/issues/43), [#44](https://github.com/artipie/docker-adapter/issues/44) are still not solved; solved: [#41](https://github.com/artipie/docker-adapter/issues/41).

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#44](https://github.com/artipie/docker-adapter/issues/44), [#47](https://github.com/artipie/docker-adapter/issues/47) are still not solved; solved: [#41](https://github.com/artipie/docker-adapter/issues/41), [#43](https://github.com/artipie/docker-adapter/issues/43).

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#44](https://github.com/artipie/docker-adapter/issues/44), [#56](https://github.com/artipie/docker-adapter/issues/56) are still not solved; solved: [#41](https://github.com/artipie/docker-adapter/issues/41), [#43](https://github.com/artipie/docker-adapter/issues/43), [#47](https://github.com/artipie/docker-adapter/issues/47).

**Comment by 0pdd** [comment]
@0pdd the puzzle [#44](https://github.com/artipie/docker-adapter/issues/44) is still not solved; solved: [#41](https://github.com/artipie/docker-adapter/issues/41), [#43](https://github.com/artipie/docker-adapter/issues/43), [#47](https://github.com/artipie/docker-adapter/issues/47), [#56](https://github.com/artipie/docker-adapter/issues/56).

**Comment by 0pdd** [comment]
@0pdd all 5 puzzles are solved here: [#41](https://github.com/artipie/docker-adapter/issues/41), [#43](https://github.com/artipie/docker-adapter/issues/43), [#44](https://github.com/artipie/docker-adapter/issues/44), [#47](https://github.com/artipie/docker-adapter/issues/47), [#56](https://github.com/artipie/docker-adapter/issues/56).
