### ISSUE TITLE
Mount Blob endpoint

### ISSUE THREAD

**Issue by olegmoz** [artipie/docker-adapter#390]
There is mount blob endpoint in Docker API which is not supported yet: `POST /v2/<name>/blobs/uploads/?mount=<digest>&from=<repository name>`

**Comment by 0pdd** [comment]
@olegmoz 2 puzzles [#393](https://github.com/artipie/docker-adapter/issues/393), [#394](https://github.com/artipie/docker-adapter/issues/394) are still not solved.

**Comment by 0pdd** [comment]
@olegmoz the puzzle [#393](https://github.com/artipie/docker-adapter/issues/393) is still not solved; solved: [#394](https://github.com/artipie/docker-adapter/issues/394).

**Comment by olegmoz** [comment]
@rultor release, tag=`0.9`

**Comment by 0pdd** [comment]
@olegmoz all 2 puzzles are solved here: [#393](https://github.com/artipie/docker-adapter/issues/393), [#394](https://github.com/artipie/docker-adapter/issues/394).
