### ISSUE TITLE
AstoBlobs.java:52-55: Continue implementing put...

### ISSUE THREAD

**Issue by 0pdd** [artipie/docker-adapter#41]
The puzzle `36-a89742ef` from #36 has to be resolved: 

https://github.com/artipie/docker-adapter/blob/ab4a4daa76e4db29845d701c4e6ed1535f891afa/src/main/java/com/artipie/docker/asto/AstoBlobs.java#L52-L55

The puzzle was created by @g4s8 on 28-Jan-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#41](https://github.com/artipie/docker-adapter/issues/41) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/c4cb3c87-772b-46f5-a06e-6125bd354ffc); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Job [#41](https://github.com/artipie/docker-adapter/issues/41) is already assigned to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0pdd** [comment]
The puzzle `36-a89742ef` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#43](https://github.com/artipie/docker-adapter/issues/43), [#44](https://github.com/artipie/docker-adapter/issues/44) are still not solved.

**Comment by 0crat** [comment]
Job was finished in 2 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#44](https://github.com/artipie/docker-adapter/issues/44), [#47](https://github.com/artipie/docker-adapter/issues/47) are still not solved; solved: [#43](https://github.com/artipie/docker-adapter/issues/43).

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#44](https://github.com/artipie/docker-adapter/issues/44), [#56](https://github.com/artipie/docker-adapter/issues/56) are still not solved; solved: [#43](https://github.com/artipie/docker-adapter/issues/43), [#47](https://github.com/artipie/docker-adapter/issues/47).

**Comment by 0pdd** [comment]
@0pdd the puzzle [#44](https://github.com/artipie/docker-adapter/issues/44) is still not solved; solved: [#43](https://github.com/artipie/docker-adapter/issues/43), [#47](https://github.com/artipie/docker-adapter/issues/47), [#56](https://github.com/artipie/docker-adapter/issues/56).

**Comment by 0pdd** [comment]
@0pdd all 4 puzzles are solved here: [#43](https://github.com/artipie/docker-adapter/issues/43), [#44](https://github.com/artipie/docker-adapter/issues/44), [#47](https://github.com/artipie/docker-adapter/issues/47), [#56](https://github.com/artipie/docker-adapter/issues/56).
