### ISSUE TITLE
AstoBlobs.java:55-58: Implement integration test for this...

### ISSUE THREAD

**Issue by 0pdd** [artipie/docker-adapter#43]
The puzzle `41-f8287a93` from #41 has to be resolved: 

https://github.com/artipie/docker-adapter/blob/fb2cfd6046a4ed7d8d386dbf665a03775f0d4677/src/main/java/com/artipie/docker/asto/AstoBlobs.java#L55-L58

The puzzle was created by @g4s8 on 28-Jan-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#43](https://github.com/artipie/docker-adapter/issues/43) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/e7418017-881d-447c-8886-5d33f17a9c3c); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0pdd** [comment]
The puzzle `41-f8287a93` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#47](https://github.com/artipie/docker-adapter/issues/47) is still not solved.

**Comment by 0crat** [comment]
Job was finished in 17 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0pdd** [comment]
@0pdd the puzzle [#56](https://github.com/artipie/docker-adapter/issues/56) is still not solved; solved: [#47](https://github.com/artipie/docker-adapter/issues/47).

**Comment by 0pdd** [comment]
@0pdd all 2 puzzles are solved here: [#47](https://github.com/artipie/docker-adapter/issues/47), [#56](https://github.com/artipie/docker-adapter/issues/56).
