### ISSUE TITLE
AstoBlobs.java:59-61: Refactor this class, make it more...

### ISSUE THREAD

**Issue by 0pdd** [artipie/docker-adapter#44]
The puzzle `41-ef5f1d74` from #41 has to be resolved: 

https://github.com/artipie/docker-adapter/blob/fb2cfd6046a4ed7d8d386dbf665a03775f0d4677/src/main/java/com/artipie/docker/asto/AstoBlobs.java#L59-L61

The puzzle was created by @g4s8 on 28-Jan-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0pdd** [comment]
The puzzle `41-ef5f1d74` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
I'm not managing `artipie/docker-adapter` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)
