### ISSUE TITLE
NPE on missing mediaType in manifest.json

### ISSUE THREAD

**Issue by g4s8** [artipie/docker-adapter#446]
If manifest JSON doesn't have `mediaType` field, the adapter fails with `NullPointerException`. Instead of this, the adapter should return `MANIFEST_INVALID` error, see https://docs.docker.com/registry/spec/api/

**Comment by g4s8** [comment]
@olenagerasimova could you please check this?

**Comment by olenagerasimova** [comment]
@rultor release, tag=0.14.1
