### ISSUE TITLE
Multiple accept headers list is not supported

### ISSUE THREAD

**Issue by g4s8** [artipie/docker-adapter#449]
When the docker receives GET manifest request with multi-media-type accept header, it treats this header as a single value, e.g. `Accept: text/html, application/xhtml+xml, application/xml;q=0.9, image/webp, */*;q=0.8` header has these media types: ` text/html`, `application/xhtml+xml`, `application/xml`, `image/webp`. The problem occurs in `Manifest.convert()` method which receives this single line multi-media-type value from `ManifestEntity` on `response()`.

**Comment by g4s8** [comment]
@rultor release, tag=`0.14.2`

**Comment by yegor256** [comment]
@g4s8 fixed

**Comment by g4s8** [comment]
@rultor release, tag=`0.14.2`

**Comment by g4s8** [comment]
@rultor release, tag=`0.14.2`
