### ISSUE TITLE
Since 0.1

### ISSUE THREAD

**Issue by g4s8** [artipie/docker-adapter#45]
Use `@since 0.1` instead of `1.0`

**Comment by g4s8** [comment]
Fixed in https://github.com/artipie/docker-adapter/commit/aa80199bb29521a6d82d94c5635d42ae8d2fa873

**Comment by 0crat** [comment]
Job `gh:artipie/docker-adapter#45` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
