### ISSUE TITLE
AstoBlobsITCase.java:42-44: Implement more integration...

### ISSUE THREAD

**Issue by 0pdd** [artipie/docker-adapter#47]
The puzzle `43-c08410f5` from #43 has to be resolved: 

https://github.com/artipie/docker-adapter/blob/be6bd7b07a3dfd41b17b3d19ca2910c972b71bcd/src/test/java/com/artipie/docker/storage/AstoBlobsITCase.java#L42-L44

The puzzle was created by @g4s8 on 29-Jan-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0pdd** [comment]
The puzzle `43-c08410f5` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job `gh:artipie/docker-adapter#47` is not assigned, can't get performer
