### ISSUE TITLE
HTTP front implementation

### ISSUE THREAD

**Issue by g4s8** [artipie/docker-adapter#54]
Implement `Slice` interface with HTTP API for docker registry: https://docs.docker.com/registry/spec/api/

We decided to use same Docker image naming convention as Artifactory: first part of docker images we treat as repository name.

**Comment by g4s8** [comment]
@0crat assign me

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/artipie/docker-adapter/issues/54#issuecomment-585102425))

@g4s8 The job [#54](https://github.com/artipie/docker-adapter/issues/54) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/3d1795eb-3596-4a9b-8b29-2e571185e1b3); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Job `gh:artipie/docker-adapter#54` is not assigned, can't get performer

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#89](https://github.com/artipie/docker-adapter/issues/89) is still not solved.

**Comment by 0pdd** [comment]
@g4s8 the only puzzle [#89](https://github.com/artipie/docker-adapter/issues/89) is solved here.

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#99](https://github.com/artipie/docker-adapter/issues/99) is still not solved; solved: [#89](https://github.com/artipie/docker-adapter/issues/89).

**Comment by 0pdd** [comment]
@g4s8 all 2 puzzles are solved here: [#89](https://github.com/artipie/docker-adapter/issues/89), [#99](https://github.com/artipie/docker-adapter/issues/99).

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#131](https://github.com/artipie/docker-adapter/issues/131) is still not solved; solved: [#89](https://github.com/artipie/docker-adapter/issues/89), [#99](https://github.com/artipie/docker-adapter/issues/99).

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#154](https://github.com/artipie/docker-adapter/issues/154) is still not solved; solved: [#131](https://github.com/artipie/docker-adapter/issues/131), [#89](https://github.com/artipie/docker-adapter/issues/89), [#99](https://github.com/artipie/docker-adapter/issues/99).

**Comment by 0pdd** [comment]
@g4s8 all 4 puzzles are solved here: [#131](https://github.com/artipie/docker-adapter/issues/131), [#154](https://github.com/artipie/docker-adapter/issues/154), [#89](https://github.com/artipie/docker-adapter/issues/89), [#99](https://github.com/artipie/docker-adapter/issues/99).
