### ISSUE TITLE
AstoRepo.java:90-92: Extract this class from AstoRepo....

### ISSUE THREAD

**Issue by 0pdd** [artipie/docker-adapter#59]
The puzzle `57-bb2ef47d` from #57 has to be resolved: 

https://github.com/artipie/docker-adapter/blob/2cd6cd5c20da6966b25b5fbbaa06775f06d5cf71/src/main/java/com/artipie/docker/asto/AstoRepo.java#L90-L92

The puzzle was created by @g4s8 on 17-Feb-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0pdd** [comment]
The puzzle `57-bb2ef47d` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job `gh:artipie/docker-adapter#59` is not assigned, can't get performer
