### ISSUE TITLE
Unclear phrases in spec

### ISSUE THREAD

**Issue by olenagerasimova** [artipie/docker-adapter#73]
These two sentences in spec.md looks unclear:

> Uploads of layers are managed in the uploads directory, which is key by upload id.

> While the registry can save all revisions of a manifest, no relationship is
implied as to the ordering of changes to a manifest.

May it's possible to improve them somehow?

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#73](https://github.com/artipie/docker-adapter/issues/73) assigned to @olegmoz[/z](https://www.0crat.com/u/olegmoz), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/e35fb8f3-975d-4aec-b122-0d17bcf70b28); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @olegmoz[/z](https://www.0crat.com/u/olegmoz) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job

**Comment by 0crat** [comment]
I'm not managing `artipie/docker-adapter` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)
