### ISSUE TITLE
Test coverage reports

### ISSUE THREAD

**Issue by g4s8** [artipie/docker-adapter#76]
Add test coverage reports and enforce some minimum coverage. Maven plugin `org.jacoco` can be used. The reports will be processed by external tools, e.g. https://codecov.io/ the minimum coverage rates fails a build in case of lack of tests.

**Comment by 0crat** [comment]
The job [#76](https://github.com/artipie/docker-adapter/issues/76) assigned to @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/37188af0-0af2-4136-b472-b9954186e9f5); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); we should be aware that @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) is on vacation; this ticket may be delayed; there will be no monetary reward for this job

**Comment by olenagerasimova** [comment]
@g4s8 should I add todo in pom to improve code coverage? If so, what are desired numbers? Currently we have
```
instructions covered ratio is 0.71
lines covered ratio is 0.69
branches covered ratio is 0.75
complexity covered ratio is 0.76
 methods covered ratio is 0.79
```

**Comment by g4s8** [comment]
@olenagerasimova I think `0.75` for all would be fine

**Comment by 0crat** [comment]
@olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#81](https://github.com/artipie/docker-adapter/issues/81) is still not solved.

**Comment by g4s8** [comment]
@olenagerasimova PR #77 was merged, closing this ticket

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0pdd** [comment]
@g4s8 the only puzzle [#81](https://github.com/artipie/docker-adapter/issues/81) is solved here.
