### ISSUE TITLE
pom.xml:183-186: Improve code coverage by writing...

### ISSUE THREAD

**Issue by 0pdd** [artipie/docker-adapter#81]
The puzzle `76-bbfaed36` from #76 has to be resolved: 

https://github.com/artipie/docker-adapter/blob/16f3fc5fe043e756308d946958ae5b94432ca5ae/pom.xml#L183-L186

The puzzle was created by @g4s8 on 15-Apr-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#81](https://github.com/artipie/docker-adapter/issues/81) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/c85f57f3-835e-404d-8bc2-1a587e3f20a1); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by paulodamaso** [comment]
@0crat wait for #84 merge

**Comment by paulodamaso** [comment]
@g4s8 My previous PR on this have rotten, and now the coverage numbers are acceptable: instruction ratio is 0.86, lines is 0.83, branches is 0.81, complexity is 0.86, methods is 0.90 and there is no class missed.

Current uncovered code is mostly inside private members of classes that are hard to reach due to design concerns, so I think that we need to fix these issues before trying to cover them with tests. Therefore, I think that this ticket is invalid for now.

**Comment by paulodamaso** [comment]
@g4s8 ping

**Comment by g4s8** [comment]
@paulodamaso you are right, thanks

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@11b87d43-ce88-41df-9552-4f2ff5dd1699, thread: PQ-CT2E6TK9B
com.zerocracy.farm.ruled.RdRules[130] java.lang.IllegalStateException: http://datum.zerocracy.com/latest/rules/pm/no-lost-boosts.xsl says: The boost for job "gh:artipie/docker-adapter#81" exists in boosts.xml, but the job is absent in the WBS among 55 jobs.
```

[0.53.13](https://github.com/zerocracy/farm): CID: [3d50718b-425d-4ce5-8525-47db1367a89e](https://www.0crat.com/footprint/CT2E6TK9B/3d50718b-425d-4ce5-8525-47db1367a89e), Type: "Remove job from WBS"

**Comment by sereshqua** [comment]
@0crat quality good
