### ISSUE TITLE
AstoUploadTest.java:44-46: Implement AstoUpload....

### ISSUE THREAD

**Issue by 0pdd** [artipie/docker-adapter#89]
The puzzle `54-60715e08` from #54 has to be resolved: 

https://github.com/artipie/docker-adapter/blob/a18a173e5d692911349d39ca0bfc6fa117e04997/src/test/java/com/artipie/docker/asto/AstoUploadTest.java#L44-L46

The puzzle was created by @olegmoz on 21-Apr-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
Job `gh:artipie/docker-adapter#89` is not assigned, can't get performer
